### ISSUE TITLE
Dynamically adding and removing channels that a bot connects to?

### ISSUE THREAD

**Issue by michael-luo** [kritzware/twitch-bot#16]
Hi there, I was wondering if this module helps satisfy the use case where you want to dynamically add or remove channel(s) that the bot is connected to.

I think currently, I would have to call close() on the bot which closes every channel and then instantiate another bot with the updated list of channels

**Comment by anXieTyPB** [comment]
Thats true, but its basically just implementing a PART-IRC-Message:
https://dev.twitch.tv/docs/irc#part-generic

I can create a PR today or tomorrow.

**Comment by kritzware** [comment]
As @anXieTyPB said above, a temporary fix would be to use the `writeIrcMessage` method, e.g.
```javascript
Bot.writeIrcMessage("PART #channel") // Leaves the channel
```
```javascript
Bot.writeIrcMessage("JOIN #channel") // Join a channel
```

Regarding new methods for the bot, such as joining/parting specific channels, I have some thoughts and ideas which I'll write here when I have some free time later 👍

**Comment by anXieTyPB** [comment]
https://github.com/anXieTyPB/twitch-bot/tree/dev-joinpart

Implemented the join() and part() functions. The join-event now emits with a string parameter that holds the channel name that was successfully joined. 

Part-event with a string parameter that holds the channel name will be emitted aswell if user decides to part from a channel during runtime. 

Also refactored redundant code and put the channelname validation into the parser file. Added tests for the features.

Currently refactoring the documentation is missing from the branch.

**Comment by michael-luo** [comment]
Great job @anXieTyPB 
Can we allow TwitchBot to be initialized without specifying a list of channels now that we can fine-tune which channels to join and part after initialization? Maybe just default it to empty list if initial `channels` is not specified?

Should we also update `this.channels` whenever we `join` or `part` a channel?

**Comment by kritzware** [comment]
Merged in 😄
