### ISSUE TITLE
random disconnet

### ISSUE THREAD

**Issue by tcarlsen** [kritzware/twitch-bot#28]
hey there.

I have this random disconnect where the bot just leaves the channel without any errors and I have to restart the script.

any ideas to how I can test what's happening?

**Comment by kritzware** [comment]
Hi @tcarlsen,

Perhaps you could use the `message` event and check if anything looks strange about the final chatter object, or the chat message itself, before a random disconnect. 

Alternatively, you could log the raw IRC data block in `node_modules/twitch-bot/lib/bot.js` e.g. 
```javascript
  listen() {
    this.irc.on('data', data => {
      console.log(data) // Add this log statement and check if there is anything unusual before a disconnect    

    ...
    })
}
```

Let me know if you find anything 👍

**Comment by tcarlsen** [comment]
Haven't done it since I wrote this issue. No idea what happened before
