### ISSUE TITLE
necessary scopes for api

### ISSUE THREAD

**Issue by BlitZz96** [kritzware/twitch-bot#40]
Would be nice to include what scopes are necessary in the docs

**Comment by kritzware** [comment]
Hi @BlitZz96, which scopes are you referring to? I haven't worked with the Twitch API in a little while.

**Comment by BlitZz96** [comment]
Hi @kritzware! I'm referring to the https://dev.twitch.tv/docs/authentication/#scopes needed when creating an oaut token. I assume you need the following:

1. `chat:read`
2. `chat:edit`
3. `channel:moderate`
5. ???

Are there any more?

**Comment by kritzware** [comment]
`chat:read` and `chat:edit` for sure. But all of the rest depend entirely on what you plan to do with your bot. If it's going to be a moderator, then you'll need `channel:moderate`. If you plan to send whisper messages, then you'll need `whispers:edit` etc. 

This package should work just fine with `chat:read` and `chat:edit` scopes, the rest are up to you! We should definitely add this to the docs, thanks for bring it up 👍

**Comment by BlitZz96** [comment]
Nice! Thank you for taking your time to review this.
