### ISSUE TITLE
Is it possible to know if a chatter is a follower?

### ISSUE THREAD

**Issue by NoxPhoenix** [kritzware/twitch-bot#41]
The payload that responds on chat messages has a property for subscribers, but what if you want to control what commands can only be used by followers?

**Comment by kritzware** [comment]
Unfortunately I don't think you can get this information via Twitch IRC. The best way for you to do this would be to query the Twitch API with the user id (provided in a chatter message) at this endpoint: https://dev.twitch.tv/docs/v5/reference/users/#check-user-follows-by-channel

I hope that helps!
