### ISSUE TITLE
Cheer event?

### ISSUE THREAD

**Issue by Vezqi** [kritzware/twitch-bot#42]
Any plan on implementing an event for cheers in channels? (Assuming the API supports it...)

**Comment by kritzware** [comment]
I'm pretty sure bits (cheers) are included in the `"message"` event? There should be a `bits` property on the chatter object, as described in the Twitch IRC docs: https://dev.twitch.tv/docs/irc/tags/#privmsg-twitch-tags

Let me know if that helps 👍

**Comment by Vezqi** [comment]
Got it, thanks!
