### ISSUE TITLE
How is it possible to recieve the ouath

### ISSUE THREAD

**Issue by Scraayp** [kritzware/twitch-bot#54]
I tried everything with a client token to client secret and i still dont know how to recieve the oauth. 
Could you make a tutorial about that / example. Will be aprieciated thanks

**Comment by kritzware** [comment]
You need to generate a Twitch Chat OAuth token, which is different to a standard Twitch API client or secret token. 

The [official Twitch documentation](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth) is worth a look, but I'd recommend just using [this app](https://twitchapps.com/tmi/) generate your token.

**Comment by Scraayp** [comment]
Hmm okay will take a look.
I would suggest you to make a tutorial for other users how the things works. Because some people just  dont get it you know.
